const fs = require('fs');
const g = require('../src/lib/data/guides.json');
const fm = g.find(x => x.id === 'type-classique-early-game-debutant');

fm.content = "Type : Classique, Early Game, Débutant\n\nLe fan meeting est un mini evennement toutes les 48h interne au groupe.\n\nLe but est de scorer le plus possible pour obtenir des récompenses boostant votre voiture.\n\nLe fan meeting peut être construit directement après la construction du HQ et être fait tout de suite.\n\nPour participer vous devez démarrer un rassemblement sur le fan meeting et rejoindre les autres rassemblement de vos alliés\n\nDeux choses influent votre scoring, la puissante de l'équipe faisant le rassemblement et votre nombre de fans dans le bus (fan capacity de votre équipe). Il est donc conseillé de rejoindre les bus les plus forts possible pour optimiser votre scoring.\n\nTips :\n\nPositionné les meilleurs joueurs proches du fan meeting pour qu'ils puissent ouvrir un maximum de rassemblement pour tout le monde\n\nChoisissez une horaire fixe qui convient a un maximum de personne, si aucun horaire ne correspond choisissez en deux pour permettre une rotation";

fm.content_en = "Type: Classic, Early Game, Beginner\n\nThe Fan Meeting is a mini-event held every 48 hours within the group.\n\nThe goal is to score as high as possible to earn rewards that boost your car.\n\nThe Fan Meeting can be built immediately after the HQ is built and can be done right away.\n\nTo participate, you must start a gathering at the Fan Meeting and join other gatherings of your allies.\n\nTwo things influence your score: the strength of the team hosting the gathering and the number of fans in your bus (your team's fan capacity). It is therefore advisable to join the strongest buses possible to maximize your score.\n\nTips:\n\nPosition the best players near the Fan Meeting so they can open as many gatherings as possible for everyone.\n\nChoose a fixed time that works for the most people. If no time works, choose two to allow for rotation.";

const LANG_ORIG = {
  it: { description: "Guida Fan Meeting", content: "Tipo: Classico, Inizio partita, Principiante\n\nL'incontro dei fan è un mini-evento che si tiene ogni 48 ore all'interno del gruppo.\n\nL'obiettivo è ottenere il punteggio più alto possibile per guadagnare ricompense che potenziano il tuo autobus.\n\nL'incontro dei fan può essere costruito subito dopo la costruzione del quartier generale e può essere organizzato immediatamente.\n\nPer partecipare, devi avviare un raduno presso l'incontro dei fan e unirti ad altri raduni dei tuoi alleati.\n\nDue fattori influenzano il tuo punteggio: la forza della squadra che ospita il raduno e il numero di fan nel tuo autobus (la capacità di fan della tua squadra). Si consiglia quindi di unirsi agli autobus più forti possibile per massimizzare il punteggio.\n\nSuggerimenti:\n\nPosiziona i giocatori più forti vicino all'incontro dei fan in modo che possano avviare il maggior numero possibile di raduni per tutti.\n\nScegli un orario fisso che vada bene per la maggior parte dei giocatori. Se nessun orario va bene, scegline due per consentire la rotazione." },
  es: { description: "Guía de Fan Meeting", content: "Tipo: Clásico, Inicio del juego, Principiante\n\nLa Reunión de Fans es un mini evento que se celebra cada 48 horas dentro del grupo.\n\nEl objetivo es obtener la mayor puntuación posible para ganar recompensas que mejoren tu coche.\n\nLa Reunión de Fans se puede construir inmediatamente después de construir el Cuartel General y se puede realizar de inmediato.\n\nPara participar, debes iniciar una reunión en la Reunión de Fans y unirte a las reuniones de tus aliados.\n\nDos factores influyen en tu puntuación: la fuerza del equipo que organiza la reunión y el número de fans en tu autobús (la capacidad de fans de tu equipo). Por lo tanto, es recomendable unirse a los autobuses más fuertes posibles para maximizar tu puntuación.\n\nConsejos:\n\nColoca a los mejores jugadores cerca de la Reunión de Fans para que puedan abrir tantas reuniones como sea posible para todos.\n\nElige una hora fija que funcione para la mayoría. Si ninguna hora funciona, elige dos para permitir la rotación." },
  pt: { description: "Guia de Fan Meeting", content: "Tipo: Clássico, Início de Jogo, Iniciante\n\nO Encontro de Fãs é um mini-evento realizado a cada 48 horas dentro do grupo.\n\nO objetivo é alcançar a maior pontuação possível para ganhar recompensas que melhoram seu veículo.\n\nO Encontro de Fãs pode ser construído imediatamente após a construção do QG e pode ser realizado sem demora.\n\nPara participar, você deve iniciar uma reunião no Encontro de Fãs e entrar em outras reuniões de seus aliados.\n\nDois fatores influenciam sua pontuação: a força da equipe que organiza o encontro e o número de fãs no seu ônibus (a capacidade de fãs da sua equipe). Portanto, é aconselhável entrar nos ônibus mais fortes possíveis para maximizar sua pontuação.\n\nDicas:\n\nPosicione os melhores jogadores perto do Encontro de Fãs para que eles possam abrir o máximo de reuniões possível para todos.\n\nEscolha um horário fixo que funcione para a maioria das pessoas. Se nenhum horário funcionar, escolha dois para permitir a rotação." },
  pl: { description: "Poradnik Fan Meeting", content: "Typ: Klasyczny, Początkujący, Początkujący\n\nSpotkanie Fanów to mini-wydarzenie odbywające się co 48 godzin w grupie.\n\nCelem jest zdobycie jak najwyższego wyniku, aby zdobyć nagrody, które wzmocnią Twój samochód.\n\nSpotkanie Fanów można zorganizować natychmiast po zbudowaniu Kwatery Głównej i można je zorganizować od razu.\n\nAby wziąć udział, musisz rozpocząć spotkanie na Spotkaniu Fanów i dołączyć do innych spotkań swoich sojuszników.\n\nNa Twój wynik wpływają dwie rzeczy: siła drużyny organizującej spotkanie oraz liczba kibiców w Twoim autobusie (pojemność kibiców Twojej drużyny). Dlatego zaleca się dołączanie do najsilniejszych autobusów, aby zmaksymalizować swój wynik.\n\nWskazówki:\n\nUmieść najlepszych graczy w pobliżu Spotkania Fanów, aby mogli otworzyć jak najwięcej spotkań dla wszystkich.\n\nWybierz stałą godzinę, która pasuje do większości osób. Jeśli żadna nie pasuje, wybierz dwie godziny, aby umożliwić rotację." },
  id: { description: "Panduan Fan Meeting", content: "Tipe: Klasik, Awal Permainan, Pemula\n\nPertemuan Penggemar adalah acara mini yang diadakan setiap 48 jam di dalam grup.\n\nTujuannya adalah untuk mendapatkan skor setinggi mungkin untuk mendapatkan hadiah yang meningkatkan mobil Anda.\n\nPertemuan Penggemar dapat dibangun segera setelah Markas Besar dibangun dan dapat dilakukan langsung.\n\nUntuk berpartisipasi, Anda harus memulai pertemuan di Pertemuan Penggemar dan bergabung dengan pertemuan lain dari sekutu Anda.\n\nDua hal yang memengaruhi skor Anda: kekuatan tim yang menyelenggarakan pertemuan dan jumlah penggemar di bus Anda (kapasitas penggemar tim Anda). Oleh karena itu, disarankan untuk bergabung dengan bus terkuat yang memungkinkan untuk memaksimalkan skor Anda.\n\nTips:\n\nTempatkan pemain terbaik di dekat Pertemuan Penggemar agar mereka dapat membuka sebanyak mungkin pertemuan untuk semua orang.\n\nPilih waktu tetap yang cocok untuk sebagian besar orang. Jika tidak ada waktu yang cocok, pilih dua waktu untuk memungkinkan rotasi." },
  ru: { description: "Гайд Fan Meeting", content: "Тип: Классический, Начальная стадия игры, Для новичков\n\nВстреча фанатов — это мини-событие, проводимое каждые 48 часов внутри группы.\n\nЦель — набрать как можно больше очков, чтобы получить награды, улучшающие вашу машину.\n\nВстречу фанатов можно построить сразу после постройки штаб-квартиры.\n\nДля участия необходимо начать сбор на Встрече фанатов и присоединиться к другим сборам ваших союзников.\n\nНа ваш счет влияют два фактора: сила команды, проводящей сбор, и количество фанатов в вашем автобусе (вместимость вашего автобуса для фанатов). Поэтому рекомендуется присоединяться к самым сильным автобусам, чтобы максимизировать свой счет.\n\nСоветы:\n\nРасположите лучших игроков рядом с Встречей фанатов, чтобы они могли открыть как можно больше сборов для всех.\n\nВыберите фиксированное время, подходящее для большинства людей. Если ни одно время не подходит, выберите два, чтобы обеспечить ротацию." },
  de: { description: "Fan-Meeting-Leitfaden", content: "Typ: Klassisch, Spielbeginn, Anfänger\n\nDas Fan-Treffen ist ein Mini-Event, das alle 48 Stunden innerhalb der Gruppe stattfindet.\n\nZiel ist es, eine möglichst hohe Punktzahl zu erreichen, um Belohnungen zu erhalten, die dein Auto verbessern.\n\nDas Fan-Treffen kann direkt nach dem Bau des Hauptquartiers (HQ) eingerichtet und sofort durchgeführt werden.\n\nUm teilzunehmen, musst du ein Treffen beim Fan-Treffen starten und dich anderen Treffen deiner Verbündeten anschließen.\n\nZwei Faktoren beeinflussen deine Punktzahl: die Stärke des Teams, das das Treffen veranstaltet, und die Anzahl der Fans in deinem Bus (die Fankapazität deines Teams). Es empfiehlt sich daher, dich den stärksten Bussen anzuschließen, um deine Punktzahl zu maximieren.\n\nTipps:\n\nPositioniere die besten Spieler in der Nähe des Fan-Treffens, damit sie möglichst viele Treffen für alle eröffnen können.\n\nWähle eine feste Uhrzeit, die für die meisten passt. Falls keine Uhrzeit passt, wähle zwei, um eine Rotation zu ermöglichen." }
};

for (const [lang, orig] of Object.entries(LANG_ORIG)) {
  fm['description_' + lang] = orig.description;
  fm['content_' + lang] = orig.content;
}

fm.readTime = '3 min';

fs.writeFileSync('./src/lib/data/guides.json', JSON.stringify(g, null, 2));
console.log('Reverted successfully');

// Verify
const g2 = JSON.parse(fs.readFileSync('./src/lib/data/guides.json', 'utf8'));
const fm2 = g2.find(x => x.id === 'type-classique-early-game-debutant');
console.log('FR:', fm2.content.length, 'EN:', fm2.content_en.length, 'readTime:', fm2.readTime);
console.log('IT:', fm2.content_it.length, 'ES:', fm2.content_es.length, 'DE:', fm2.content_de.length);
